In [3]:
import numpy as np

vize = [10, 20, 30, 40]
final = [2, 60, 32, 50]

vize_np = np.array(vize)
final_np = np.array(final)

ortalama = (vize_np + final_np) / 2 
print(ortalama)


[ 6. 40. 31. 45.]


In [7]:
import numpy as np

my_array = np.array([[1,2,3],[4,5,6]])

print(my_array)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np

my_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5])
max_value = np.amax(arr)
print(max_value)

5


In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
max_values=np.amax(arr,axis=1)
print(max_values)

[3 6 9]


In [14]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
max_values=np.amax(arr,axis=1, keepdims=True)
print(max_values)

[[3]
 [6]
 [9]]


In [18]:
import numpy as np
arr = np.array([1,2,3,4,5])
max_value = np.amax(arr, initial=0)
print(max_value)

5
